services:
  # -----------------------------
  # INFRAESTRUTURA - BROKER (RabbitMQ)
  # -----------------------------
  rabbitmq:
    image: rabbitmq:3.12-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - hap-network

  # -----------------------------
  # INFRAESTRUTURA - BASE DE DADOS (Auth DB)
  # -----------------------------
  postgres-auth:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5438:5432"
    networks:
      - hap-network

  # -----------------------------
  # INFRAESTRUTURA - DISCOVERY (Eureka)
  # -----------------------------
  discovery-service:
    build: ./discovery-server
    ports:
      - "8761:8761"
    networks:
      - hap-network

  # -----------------------------
  # API GATEWAY
  # -----------------------------
  gateway-service:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SERVER_PORT=8080
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
    depends_on:
      - discovery-service
    networks:
      - hap-network

  # -----------------------------
  # SEGURANÇA (Auth Service)
  # -----------------------------
  auth-service:
    build: ./auth-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-auth:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - JWT_SECRET=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
      - APP_ADMIN_USER=admin
      - APP_ADMIN_PASS=admin123
      - SERVER_PORT=8080
    depends_on:
      - discovery-service
      - postgres-auth
    networks:
      - hap-network

  # -----------------------------
  # MICROSSERVIÇOS DE NEGÓCIO
  # -----------------------------
  physician-service:
    build: ./physicians-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_PROFILES_ACTIVE=docker
      - INSTANCE_ID=physician1
    depends_on:
      - rabbitmq
      - discovery-service
    networks:
      - hap-network

  patient-service:
    build: ./patient-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - discovery-service
    networks:
      - hap-network

  appointment-service:
    build: ./appointment-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - discovery-service
    networks:
      - hap-network

  # -----------------------------
  # TRACING SERVER (Zipkin)
  # -----------------------------
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - hap-network

networks:
  hap-network:
    driver: bridge