apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
data:
  SPRING_RABBITMQ_HOST: "rabbitmq"
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://discovery-server:8761/eureka/"
  SPRING_PROFILES_ACTIVE: "default"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://auth-db:5432/authdb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
  JWT_SECRET: "sidis-v2-super-secret-key-2026-com-pelo-menos-32-chars"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"